-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

-- Create user_role enum type
DO $$ BEGIN
    CREATE TYPE user_role AS ENUM ('CUSTOMER', 'ADMIN', 'SELLER');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS public.broadcasts
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    sender_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT broadcasts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.categories
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_by bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT categories_name_created_by_key UNIQUE (name, created_by)
);

CREATE TABLE IF NOT EXISTS public.chat_attachment
(
    id uuid NOT NULL,
    message_id uuid,
    file_url text COLLATE pg_catalog."default" NOT NULL,
    file_type character varying(20) COLLATE pg_catalog."default",
    uploaded_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chat_attachment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.chat_messages
(
    id uuid NOT NULL,
    chat_room_id uuid,
    sender_id bigint,
    message text COLLATE pg_catalog."default",
    message_type character varying(20) COLLATE pg_catalog."default",
    is_read boolean DEFAULT false,
    is_delivered boolean DEFAULT false,
    deleted_at timestamp without time zone,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'DRAFT'::character varying,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    delivered_at timestamp without time zone,
    read_at timestamp without time zone,
    CONSTRAINT chat_messages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.chat_participant
(
    id bigint NOT NULL DEFAULT nextval('chat_participant_id_seq'::regclass),
    chat_room_id uuid,
    user_id bigint,
    joined_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chat_participant_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.chat_room
(
    id uuid NOT NULL,
    type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    created_by bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chat_room_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.contact_invitations
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    contact_id bigint NOT NULL,
    invite_token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    method character varying(10) COLLATE pg_catalog."default" NOT NULL,
    invite_sent_at timestamp without time zone NOT NULL,
    invite_cancelled_at timestamp without time zone,
    invite_accepted_at timestamp without time zone,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT contact_invitations_pkey PRIMARY KEY (id),
    CONSTRAINT contact_invitations_invite_token_key UNIQUE (invite_token)
);

CREATE TABLE IF NOT EXISTS public.contacts
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    seller_id bigint NOT NULL,
    invited_user_id bigint,
    phone_number character varying(20) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(100) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'NEW'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT contacts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.otp_verification
(
    id bigint NOT NULL DEFAULT nextval('otp_verification_id_seq'::regclass),
    user_id bigint NOT NULL,
    otp_code character varying(10) COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    failed_attempts integer DEFAULT 0,
    locked boolean DEFAULT false,
    lock_time timestamp without time zone,
    verified boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT otp_verification_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_likes
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    product_id bigint NOT NULL,
    user_id bigint NOT NULL,
    liked_at timestamp without time zone DEFAULT now(),
    CONSTRAINT product_likes_pkey PRIMARY KEY (id),
    CONSTRAINT product_likes_product_id_user_id_key UNIQUE (product_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.product_media
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    product_id bigint NOT NULL,
    file_url text COLLATE pg_catalog."default" NOT NULL,
    file_type character varying(20) COLLATE pg_catalog."default",
    uploaded_at timestamp without time zone DEFAULT now(),
    CONSTRAINT product_media_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    seller_id bigint NOT NULL,
    category_id bigint NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    price numeric(10, 2),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT products_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    username character varying(50) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    phone_number character varying(20) COLLATE pg_catalog."default" NOT NULL,
    role user_role NOT NULL DEFAULT 'CUSTOMER',
    profile_picture text COLLATE pg_catalog."default",
    about_me text COLLATE pg_catalog."default",
    is_deleted boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_phone_number_key UNIQUE (phone_number)
);

ALTER TABLE IF EXISTS public.broadcasts
    ADD CONSTRAINT broadcasts_sender_id_fkey FOREIGN KEY (sender_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.categories
    ADD CONSTRAINT categories_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.chat_attachment
    ADD CONSTRAINT chat_attachment_message_id_fkey FOREIGN KEY (message_id)
    REFERENCES public.chat_messages (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.chat_messages
    ADD CONSTRAINT chat_messages_chat_room_id_fkey FOREIGN KEY (chat_room_id)
    REFERENCES public.chat_room (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.chat_messages
    ADD CONSTRAINT chat_messages_sender_id_fkey FOREIGN KEY (sender_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_chat_message_sender
    ON public.chat_messages(sender_id);


ALTER TABLE IF EXISTS public.chat_participant
    ADD CONSTRAINT chat_participant_chat_room_id_fkey FOREIGN KEY (chat_room_id)
    REFERENCES public.chat_room (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.chat_participant
    ADD CONSTRAINT chat_participant_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_chat_participant_user
    ON public.chat_participant(user_id);


ALTER TABLE IF EXISTS public.chat_room
    ADD CONSTRAINT chat_room_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.contact_invitations
    ADD CONSTRAINT contact_invitations_contact_id_fkey FOREIGN KEY (contact_id)
    REFERENCES public.contacts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.contacts
    ADD CONSTRAINT contacts_invited_user_id_fkey FOREIGN KEY (invited_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.contacts
    ADD CONSTRAINT contacts_seller_id_fkey FOREIGN KEY (seller_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.otp_verification
    ADD CONSTRAINT otp_verification_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product_likes
    ADD CONSTRAINT product_likes_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.product_likes
    ADD CONSTRAINT product_likes_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.product_media
    ADD CONSTRAINT product_media_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT products_seller_id_fkey FOREIGN KEY (seller_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;