AWSTemplateFormatVersion: '2010-09-09'
Description: Nexsa V2 - Root stack (lowest-cost prod) using nested stacks

Parameters:
  ProjectName:
    Type: String
    Default: nexsa
  EnvironmentName:
    Type: String
    Default: prod

  # DNS / TLS
  DomainName:
    Type: String
    Default: api.nexsa.social
  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID for nexsa.social

  # Networking
  VpcCidr:
    Type: String
    Default: 10.50.0.0/16
  PublicSubnetCidrA:
    Type: String
    Default: 10.50.0.0/20
  PublicSubnetCidrB:
    Type: String
    Default: 10.50.16.0/20
  PrivateDbSubnetCidrA:
    Type: String
    Default: 10.50.32.0/20
  PrivateDbSubnetCidrB:
    Type: String
    Default: 10.50.48.0/20

  # App
  ContainerPort:
    Type: Number
    Default: 3000
  HealthCheckPath:
    Type: String
    Default: /health

  # Compute
  InstanceType:
    Type: String
    Default: t3.small
  AsgMinSize:
    Type: Number
    Default: 1
  AsgDesiredCapacity:
    Type: Number
    Default: 1
  AsgMaxSize:
    Type: Number
    Default: 2
  ServiceDesiredCount:
    Type: Number
    Default: 1

  # Database
  DbName:
    Type: String
    Default: nexsa_v2
  DbUsername:
    Type: String
    Default: nexsaadmin
  DbInstanceClass:
    Type: String
    Default: db.t4g.small
  DbAllocatedStorageGb:
    Type: Number
    Default: 50
  DbBackupRetentionDays:
    Type: Number
    Default: 7

  # Observability
  LogRetentionDays:
    Type: Number
    Default: 14

Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: network.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        VpcCidr: !Ref VpcCidr
        PublicSubnetCidrA: !Ref PublicSubnetCidrA
        PublicSubnetCidrB: !Ref PublicSubnetCidrB
        PrivateDbSubnetCidrA: !Ref PrivateDbSubnetCidrA
        PrivateDbSubnetCidrB: !Ref PrivateDbSubnetCidrB

  SecurityStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - NetworkStack
    Properties:
      TemplateURL: security.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        ContainerPort: !Ref ContainerPort

  EcrStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ecr.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName

  RdsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - NetworkStack
      - SecurityStack
    Properties:
      TemplateURL: rds.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        DbSubnetAId: !GetAtt NetworkStack.Outputs.PrivateDbSubnetAId
        DbSubnetBId: !GetAtt NetworkStack.Outputs.PrivateDbSubnetBId
        RdsSecurityGroupId: !GetAtt SecurityStack.Outputs.RdsSecurityGroupId
        DbName: !Ref DbName
        DbUsername: !Ref DbUsername
        DbInstanceClass: !Ref DbInstanceClass
        DbAllocatedStorageGb: !Ref DbAllocatedStorageGb
        DbBackupRetentionDays: !Ref DbBackupRetentionDays

  ObservabilityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: observability.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        LogRetentionDays: !Ref LogRetentionDays

  AlbStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - NetworkStack
      - SecurityStack
    Properties:
      TemplateURL: alb-acm-route53.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicSubnetAId: !GetAtt NetworkStack.Outputs.PublicSubnetAId
        PublicSubnetBId: !GetAtt NetworkStack.Outputs.PublicSubnetBId
        AlbSecurityGroupId: !GetAtt SecurityStack.Outputs.AlbSecurityGroupId
        DomainName: !Ref DomainName
        HostedZoneId: !Ref HostedZoneId
        ContainerPort: !Ref ContainerPort
        HealthCheckPath: !Ref HealthCheckPath

  EcsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - AlbStack
      - EcrStack
      - RdsStack
      - SecurityStack
      - NetworkStack
      - ObservabilityStack
    Properties:
      TemplateURL: ecs.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicSubnetAId: !GetAtt NetworkStack.Outputs.PublicSubnetAId
        PublicSubnetBId: !GetAtt NetworkStack.Outputs.PublicSubnetBId
        EcsSecurityGroupId: !GetAtt SecurityStack.Outputs.EcsSecurityGroupId
        EcsInstanceProfileName: !GetAtt SecurityStack.Outputs.EcsInstanceProfileName
        TaskExecutionRoleArn: !GetAtt SecurityStack.Outputs.TaskExecutionRoleArn
        TaskRoleArn: !GetAtt SecurityStack.Outputs.TaskRoleArn
        RepositoryUri: !GetAtt EcrStack.Outputs.RepositoryUri
        TargetGroupArn: !GetAtt AlbStack.Outputs.TargetGroupArn
        LogGroupName: !GetAtt ObservabilityStack.Outputs.LogGroupName
        ContainerPort: !Ref ContainerPort
        InstanceType: !Ref InstanceType
        AsgMinSize: !Ref AsgMinSize
        AsgDesiredCapacity: !Ref AsgDesiredCapacity
        AsgMaxSize: !Ref AsgMaxSize
        ServiceDesiredCount: !Ref ServiceDesiredCount
        DbHost: !GetAtt RdsStack.Outputs.DbHost
        DbPort: !GetAtt RdsStack.Outputs.DbPort
        DbName: !GetAtt RdsStack.Outputs.DbName
        DbUsername: !Ref DbUsername
        DbPasswordSecretArn: !GetAtt RdsStack.Outputs.DbPasswordSecretArn

Outputs:
  EcrRepositoryUri:
    Value: !GetAtt EcrStack.Outputs.RepositoryUri
  AlbDnsName:
    Value: !GetAtt AlbStack.Outputs.AlbDnsName
  EcsClusterName:
    Value: !GetAtt EcsStack.Outputs.ClusterName
  EcsServiceName:
    Value: !GetAtt EcsStack.Outputs.ServiceName
  MigrationTaskDefinitionArn:
    Value: !GetAtt EcsStack.Outputs.MigrationTaskDefinitionArn
  PublicSubnetAId:
    Value: !GetAtt NetworkStack.Outputs.PublicSubnetAId
  PublicSubnetBId:
    Value: !GetAtt NetworkStack.Outputs.PublicSubnetBId
  EcsSecurityGroupId:
    Value: !GetAtt SecurityStack.Outputs.EcsSecurityGroupId
  RdsEndpoint:
    Value: !GetAtt RdsStack.Outputs.DbHost


