export enum InjectionToken {
  OTP_SERVICE = 'OTP_SERVICE',
  S3_SERVICE = 'S3_SERVICE',
  ICUSTOMER_PREFERENCE_SERVICE = 'CUSTOMER_PREFERENCE_SERVICE',
  INVITATION_SERVICE = 'IInvitationService',
  MESSAGING_SERVICE = 'IMessagingService',
  FILE_SERVICE = 'FILE_SERVICE',
  INVITATION_STRATEGIES = 'INVITATION_STRATEGIES',
  EMAIL_SERVICE = 'EMAIL_SERVICE',
  // Add other injection tokens here as needed
}
